name: CI

on: [push, pull_request]

jobs:
  env: |
    SDL_VERSION: 2.0.12
    IMG_VERSION: 2.0.5
    MIX_VERSION: 2.0.4
    TTF_VERSION: 2.0.15

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: $GITHUB_WORKSPACE
        run: |
          cmake --version
          ninja --version
          g++ --version

          curl -L https://www.libsdl.org/release/SDL2-$SDL_VERSION.tar.gz | tar xz
          cd SDL2-$SDL_VERSION
          ./configure
          make
          sudo make install
          cd ..

          curl -L https://www.libsdl.org/projects/SDL_image/release/SDL2_image-$IMG_VERSION.tar.gz | tar xz
          cd SDL2_image-$IMG_VERSION
          ./configure
          make
          sudo make install
          cd ..

          curl -L https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-$TTF_VERSION.tar.gz | tar xz
          cd SDL2_ttf-$TTF_VERSION
          ./configure
          make
          sudo make install
          cd ..

          curl -L https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-$MIX_VERSION.tar.gz | tar xz
          cd SDL2_mixer-$MIX_VERSION
          ./configure
          make
          sudo make install
          cd ..

      - name: Build and run tests
        working-directory: $GITHUB_WORKSPACE
        run: |
          echo Building project...
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja
          ninja

          echo Running tests...
          cd test
          ./testWanderer
