name: "CI: macOS"

on: [ push, pull_request ]

# See https://github.com/actions/virtual-environments/blob/main/images/macos
env:
  BOOST_ROOT: /opt/homebrew/Cellar/boost/1.76.0
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/vcpkg/bincache # https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#configuration
  VCPKG_COMMIT: c93faafe6
  VCPKG_CACHE_EDITION: 1
  VCPKG_TARGET_TRIPLET: x64-osx

jobs:
  macos-test:
    runs-on: macos-latest
    if: contains(github.event.head_commit.message, '[skip-ci]') == false
    steps:
      - uses: actions/checkout@main

      # TODO cache boost
      - name: Install Boost
        run: brew install boost

      - name: Restore cached Vcpkg
        id: restore-vcpkg-and-artifacts
        uses: actions/cache@main
        with:
          path: |
            ${{env.VCPKG_ROOT}}
            !${{env.VCPKG_ROOT}}\buildtrees
            !${{env.VCPKG_ROOT}}\packages
            !${{env.VCPKG_ROOT}}\downloads
            !${{env.VCPKG_ROOT}}\installed
          key: wanderer-macos-vcpkg-${{hashFiles('vcpkg.json')}}-${{env.VCPKG_COMMIT}}-${{env.VCPKG_CACHE_EDITION}}

      - name: Install Vcpkg
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg
          git checkout -b tmp-branch ${{env.VCPKG_COMMIT}}
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

      - name: Create directory ${{env.VCPKG_DEFAULT_BINARY_CACHE}}
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        run: mkdir ${{env.VCPKG_DEFAULT_BINARY_CACHE}}

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: ./build
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja

      - name: Build
        working-directory: ./build
        run: ninja

      - name: Run tests
        working-directory: ./build/test
        run: ./WandererTests