name: "CI: Windows"

on: [ push, pull_request ]

env:
  BOOST_ROOT: C:\boost
  BOOST_VERSION: 1.78.0
  BOOST_VERSION_IN_URL: 1_78_0
  BOOST_CACHE_EDITION: 1
  VCPKG_COMMIT: c93faafe6d892aca636765e3a7e67797736b0b09
  VCPKG_TARGET_TRIPLET: x64-windows-static-md
#  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}\vcpkg\bincache

jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/get-cmake@latest

      - name: Restore cached Boost
        id: restore-cached-boost
        uses: actions/cache@v2
        with:
          path: ${{env.BOOST_ROOT}}
          key: wanderer-windows-boost-${{env.BOOST_VERSION}}-${{env.BOOST_CACHE_EDITION}}

      - name: Install Boost
        if: steps.restore-cached-boost.outputs.cache-hit == 'false'
        shell: powershell
        run: |
          mkdir boost
          cd boost
          Invoke-WebRequest -Uri "https://boostorg.jfrog.io/artifactory/main/release/${{env.BOOST_VERSION}}/source/boost_${{env.BOOST_VERSION_IN_URL}.zip" `
                            -OutFile boost.zip
          7z x -y boost.zip

      - name: Create build directory
        run: mkdir build

      - name: Generate build files
        working-directory: ./build
        run: cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja

      - name: Build
        working-directory: ./build
        run: ninja

      - name: Run tests
        working-directory: ./build/test
        run: WandererTests.exe